services:
  - docker

install:
  - docker-compose -f docker-compose.install.yml up
  - docker-compose -f docker-compose.install.yml run composer cp .env.ci .env
  - docker-compose -f docker-compose.install.yml run composer php artisan key:generate
  - docker-compose -f docker-compose.install.yml run composer composer require php-coveralls/php-coveralls
  - docker-compose stop

script:
  - docker-compose up -d # for debug
  - sleep 30 # dirty hack, TODO: properly check if the db is up and ready to avoid race condition
  - docker-compose run -e MAILCHIMP_APIKEY=${MAILCHIMP_APIKEY} -e LOG_SLACK_WEBHOOK_URL=${LOG_SLACK_WEBHOOK_URL} app php /var/www/html/vendor/phpunit/phpunit/phpunit --configuration /var/www/html/phpunit.xml --coverage-clover /var/www/html/build/logs/clover.xml

after_success:
  - travis_retry docker-compose run -e TRAVIS=${TRAVIS} -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} app php /var/www/html/vendor/bin/php-coveralls -v

notifications:
  email: false