version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '9001:80'
    volumes:
      - .:/var/www/html
      - .docker/php.ini:/usr/local/etc/php/php.ini
      - .docker/apache-vhost.conf:/etc/apache2/sites-available/custom-vhost.conf
    container_name: wsapp_mailchimp
    environment:
      DB_HOST: mysql
      DB_DATABASE: mailchimp
      DB_USERNAME: mailchimp
      DB_PASSWORD: mailchimp
      DB_PORT: 3306
      # play with mailhog
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - '4307:3306'
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mailchimp
      MYSQL_USER: mailchimp
      MYSQL_PASSWORD: mailchimp
    container_name: wsmysql_mailchimp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9010:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: '3306'
      PMA_USER: mailchimp
      PMA_PASSWORD: mailchimp
    container_name: wsphpmyadmin_mailchimp

  mailhog:
    image: mailhog/mailhog
    ports:
      - '9020:9025'
    container_name: wsmailhog_mailchimp
