version: '3'

services:
  composer:
    build:
      context: .
      dockerfile: .docker/composer/Dockerfile
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs
    container_name: wscomposer_install_mailchimp
