version: '3'

services:
  composer:
    image: composer
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs
    container_name: wscomposer_install

  node:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - '8030:8081'
    command: npm install
    container_name: wsnode_install
