auth:
  mailchimp:
    apikey: apikey
  crm:
    clientId: 'crmclientid'
    clientSecret: 'crmclientsecret'
    url: 'crmclienturl'

dataOwner:
  email: dataowner@example.com
  name: dataowner

mailchimp:
  listId: 6f33e28fa3
  syncAll: false
  ignoreSubscribeThroughMailchimp: true

mailchimpToCrm:
  interestsToSync: #order corresponds to language order in config
    - 55f795def4
    - 1851be732e
  newtag: New
  changedWithinMonths: 6
  optInOlderThanMonths: 2
  groupForNewMembers: 7654321 #could be one of the prioritizedGroups

webling:
  prioritizedGroups:
    - 7654321

fields:
  - crmKey: email1
    type: email
    sync: both
  - crmKey: firstName
    mailchimpKey: FNAME
    type: merge
    default: ''
    sync: toMailchimp
  - crmKey: lastName
    mailchimpKey: LNAME
    type: merge
    default: ''
    sync: toMailchimp
  - crmKey: gender
    mailchimpKey: GENDER
    type: merge
    default: n
    sync: toMailchimp
  - crmKey: newsletterCountryD
    mailchimpCategoryId: 55f795def4
    type: group
    trueCondition: yes
    falseCondition: no
    sync: both
  - crmKey: newsletterCountryF
    mailchimpCategoryId: 1851be732e
    type: group
    trueCondition: yes
    falseCondition: no
    sync: both
  - crmKey: pressReleaseCountryD
    mailchimpCategoryId: 294df36247
    type: group
    trueCondition: yes
    falseCondition: no
    sync: both
  - crmKey: pressReleaseCountryF
    mailchimpCategoryId: 633e3c8dd7
    type: group
    trueCondition: yes
    falseCondition: no
    sync: both
  - crmKey: language
    mailchimpTagName: Deutsch
    type: tag
    conditions:
      - d
    sync: toMailchimp
  - crmKey: language
    mailchimpTagName: Française
    type: tag
    conditions:
      - f
    sync: toMailchimp
  - crmKey: language
    mailchimpTagName: Italiano
    type: tag
    conditions:
      - i
    sync: toMailchimp
  - crmKey: notesCountry
    mailchimpCategoryId: bba5d2d564
    type: group
    trueContainsString: PolitletterDE
    falseContainsString: PolitletterUnsubscribedDE
    sync: both
  - crmKey: memberStatusCountry
    mailchimpTagName: member
    type: tag
    conditions:
      - member
      - unconfirmed
    sync: toMailchimp
  - crmKey: interests
    type: autotag
    sync: toMailchimp
  - crmKey: donorCountry
    mailchimpTagName: donor
    type: tag
    conditions:
      - donor
      - sponsor
      - majorDonor
    sync: toMailchimp
  - crmKey: notesCountry
    mailchimpKey: NOTES
    type: merge
    sync: toMailchimp
  - crmKey: firstLevelGroupNames
    type: autotag
    sync: toMailchimp
  - crmKey: recordCategory
    mailchimpTagName: media
    type: tag
    conditions:
      - media
    sync: toMailchimp
  - crmKey: id
    mailchimpKey: WEBLINGID
    type: merge
    sync: toMailchimp
  - crmKey: email1
    mailchimpKey: TOKEN
    type: token
    valid: '2022-12-31'
    secret: wPBYKufboAUD9hXx56I8w8R623qntpbq # replace me with a real secret
    sync: toMailchimp