auth:
  mailchimp:
    clientId: '***'
    clientSecret: '***'
    url: https://us18.api.mailchimp.com/3.0/
  webling:
    clientId: '***'
    clientSecret: '***'
    url: 'xxx'

mailchimpListId: 6f33e28fa3
mailchimpInteresstCategoriesId: de75614d35

fields:
  - weblingKey: firstName
    mailchimpKey: FNAME
    type: merge
  - weblingKey: lastName
    mailchimpKey: LNAME
    type: merge
  - weblingKey: gender
    mailchimpKey: GENDER
    type: merge
    default: n
  - weblingKey: email1
    mailchimpKey: EMAIL
    type: merge
  - weblingKey: newsletterCountryD
    mailchimpCategoryId: 55f795def4
    type: group
    conditions:
      - yes
  - weblingKey: newsletterCountryF
    mailchimpCategoryId: 1851be732e
    type: group
    conditions:
      - yes
  - weblingKey: pressReleaseCountryD
    mailchimpCategoryId: 294df36247
    type: group
    conditions:
      - yes
  - weblingKey: pressReleaseCountryF
    mailchimpCategoryId: 633e3c8dd7
    type: group
    conditions:
      - yes
  - weblingKey: memberStatusCountry
    mailchimpTagName: member
    type: tag
    conditions:
      - member
      - unconfirmed
  - weblingKey: interests
    type: autotag
  - weblingKey: donorCountry
    mailchimpTagName: donor
    type: tag
    conditions:
      - donor
      - sponsor
      - majorDonor
  - weblingKey: notesCountry
    mailchimpKey: NOTES
    type: merge
  - weblingKey: canton
    type: autotag
  - weblingKey: recordCategory
    mailchimpTagName: journalist
    type: tag
    conditions:
      - media
  - weblingKey: id
    mailchimpKey: WEBLINGID
    type: MERGE


