name: Pipeline

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2


      - name: PHP dependencies
        run: docker-compose -f docker-compose.install.yml up

      - name: env
        run: docker-compose -f docker-compose.install.yml run composer cp .env.ci .env

      - name: laravel key
        run: docker-compose -f docker-compose.install.yml run composer php artisan key:generate

      - name: CI specific stuff
        run: |
          docker-compose -f docker-compose.install.yml run composer composer require php-coveralls/php-coveralls
          docker-compose stop

      - name: unit tests and coverage report
        run: |
          docker-compose up -d
          docker-compose run -e MAILCHIMP_APIKEY=${MAILCHIMP_APIKEY} -e LOG_SLACK_WEBHOOK_URL=${LOG_SLACK_WEBHOOK_URL} app php /var/www/html/vendor/phpunit/phpunit/phpunit --configuration /var/www/html/phpunit.xml --coverage-clover /var/www/html/build/logs/clover.xml
          docker-compose run app php /var/www/html/vendor/bin/php-coveralls -v